#!/usr/bin/env python3
"""
Regenerate the *extra* images inside a CapCut draft using FLUX schnell (f-1).

Context:
  Some drafts increase the srt2images segment count after interval tightening (e.g., 15–25s).
  When we fill the extra segments by creating additional image files/materials, the user may
  want those extra images generated by FLUX schnell (instead of stock frames).

This tool:
  - Detects "extra" indices: image files numbered > len(image_cues.json.cues)
  - Regenerates those PNGs in-place via ImageClient (task=visual_image_gen)
  - Forces routing to FLUX schnell slot `f-1` (no Gemini)
  - Keeps CapCut draft JSON/material IDs untouched (paths stay the same)

No text-LLM is used.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import os
import random
import re
import time
from pathlib import Path

from factory_common.image_client import ImageClient, ImageGenerationError, ImageTaskOptions


def _load_json(path: Path) -> dict:
    return json.loads(path.read_text(encoding="utf-8"))


def _stable_seed(label: str) -> int:
    h = hashlib.sha256(label.encode("utf-8")).hexdigest()[:8]
    v = int(h, 16) % 2147483647
    return v or 1


def _pick_variation(rng: random.Random) -> str:
    angles = ["overhead", "eye-level", "low-angle", "3/4 angle", "side view"]
    distances = ["close-up", "medium shot", "wide shot"]
    lighting = ["soft morning light", "warm dusk light", "cool twilight", "candle-like soft glow", "diffuse cloudy daylight"]
    return f"{rng.choice(angles)}, {rng.choice(distances)}, {rng.choice(lighting)}"


def _find_image_files(assets_dir: Path) -> dict[int, Path]:
    out: dict[int, Path] = {}
    for p in assets_dir.glob("*.png"):
        m = re.match(r"^(\d{4})_", p.name)
        if not m:
            continue
        try:
            idx = int(m.group(1))
        except Exception:
            continue
        out[idx] = p
    return out


def _build_prompt(*, visual_focus: str, style: str, variation: str) -> str:
    vf = (visual_focus or "").strip()
    subj = vf if vf else "mystical symbolic scene (no humans)"
    # Keep prompts short to avoid truncation collapsing uniqueness.
    return "\n".join(
        [
            f"Subject: {subj}.",
            f"Shot: {variation}.",
            f"Style: {style}.",
            "Rules: No text, no letters, no signage, no logos, no watermark. No humans unless explicitly needed.",
        ]
    ).strip()


def _is_rate_limited(exc: BaseException) -> bool:
    msg = str(exc).lower()
    return (
        "rate_limit_exceeded" in msg
        or "rate limit" in msg
        or "fireworks error 429" in msg
        or " http 429" in msg
        or " 429:" in msg
    )


def _rate_limit_wait(request_times: list[float], *, max_per_minute: int) -> None:
    if max_per_minute <= 0:
        return
    window = 60.0
    now = time.monotonic()
    request_times[:] = [t for t in request_times if (now - t) < window]
    if len(request_times) < max_per_minute:
        return
    oldest = min(request_times)
    sleep_for = window - (now - oldest)
    if sleep_for > 0:
        time.sleep(float(sleep_for))
    now2 = time.monotonic()
    request_times[:] = [t for t in request_times if (now2 - t) < window]


def main() -> int:
    ap = argparse.ArgumentParser(description="Regenerate extra draft images with FLUX schnell (f-1)")
    ap.add_argument("--draft", action="append", required=True, help="CapCut draft dir (repeatable)")
    ap.add_argument("--min-bytes", type=int, default=80_000, help="Minimum output PNG bytes sanity check")
    ap.add_argument("--sleep-sec", type=float, default=0.0, help="Sleep between requests (rate limiting)")
    ap.add_argument("--max-per-minute", type=int, default=6, help="Hard cap of requests per minute (safe default)")
    ap.add_argument("--max-retries", type=int, default=8, help="Max retries per image on 429/rate limit")
    ap.add_argument("--timeout-sec", type=int, default=300)
    ap.add_argument("--dry-run", action="store_true")
    args = ap.parse_args()

    # Force routing to FLUX schnell slot; do not allow fallback.
    os.environ["IMAGE_CLIENT_FORCE_MODEL_KEY_VISUAL_IMAGE_GEN"] = "f-1"
    os.environ["SRT2IMAGES_IMAGE_ALLOW_FALLBACK"] = "0"

    client = ImageClient()
    request_times: list[float] = []

    for draft_str in args.draft:
        draft_dir = Path(draft_str).expanduser()
        if not draft_dir.exists():
            print(f"❌ draft not found: {draft_dir}")
            return 2

        cues_path = draft_dir / "image_cues.json"
        if not cues_path.exists():
            print(f"❌ image_cues.json not found: {draft_dir}")
            return 2
        cues = _load_json(cues_path).get("cues") or []
        if not isinstance(cues, list) or not cues:
            print(f"❌ invalid cues: {cues_path}")
            return 2

        base_count = len(cues)
        assets_dir = draft_dir / "assets" / "image"
        if not assets_dir.exists():
            print(f"❌ assets/image not found: {draft_dir}")
            return 2

        files_by_idx = _find_image_files(assets_dir)
        if not files_by_idx:
            print(f"❌ no images found in {assets_dir}")
            return 2

        max_idx = max(files_by_idx)
        extra_indices = [i for i in range(base_count + 1, max_idx + 1) if i in files_by_idx]
        if not extra_indices:
            print(f"✅ {draft_dir.name}: no extra indices (base={base_count}, max={max_idx})")
            continue

        # Style for CH04 (kept in English to reduce JP signage bias).
        style = "rich mystical oil painting, akashic records, dark philosophical calm, cinematic composition, high detail"

        rng = random.Random(_stable_seed(draft_dir.name))
        regenerated = 0

        for idx in extra_indices:
            # Map extra index to an existing cue (cycle from start).
            cue_pos = (idx - base_count) - 1  # 0-based
            cue_pos = cue_pos % base_count
            cue = cues[cue_pos] if 0 <= cue_pos < base_count else {}
            visual_focus = str((cue or {}).get("visual_focus") or "").strip()

            variation = _pick_variation(rng)
            prompt = _build_prompt(visual_focus=visual_focus, style=style, variation=variation)
            out_path = files_by_idx[idx]

            if args.dry_run:
                print(f"[DRY] {draft_dir.name} idx={idx:04d} -> cue#{cue_pos+1:04d} path={out_path.name}")
                continue

            seed = _stable_seed(f"{draft_dir.name}:{idx:04d}")
            options = ImageTaskOptions(
                task="visual_image_gen",
                prompt=prompt,
                aspect_ratio="16:9",
                n=1,
                seed=seed,
                extra={"timeout_sec": int(args.timeout_sec)},
            )

            attempt = 0
            while True:
                attempt += 1
                _rate_limit_wait(request_times, max_per_minute=int(args.max_per_minute))
                request_times.append(time.monotonic())
                try:
                    result = client.generate(options)
                    break
                except ImageGenerationError as exc:
                    if _is_rate_limited(exc) and attempt < int(args.max_retries):
                        # Fireworks 429 may not include Retry-After; use conservative backoff.
                        backoff = min(120.0, max(15.0, 10.0 * attempt))
                        time.sleep(backoff)
                        continue
                    raise
            if not result.images or not result.images[0]:
                print(f"❌ no image bytes returned (idx={idx:04d}, draft={draft_dir.name})")
                return 2

            tmp = out_path.with_suffix(out_path.suffix + ".tmp")
            tmp.write_bytes(result.images[0])
            if tmp.stat().st_size < int(args.min_bytes):
                print(f"❌ generated PNG too small: {tmp} ({tmp.stat().st_size} bytes)")
                return 2
            tmp.replace(out_path)
            regenerated += 1

            if args.sleep_sec and args.sleep_sec > 0:
                time.sleep(float(args.sleep_sec))

        print(f"✅ {draft_dir.name}: regenerated {regenerated} images via FLUX schnell (extra indices only)")

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
